import type { UserRole } from "@/types/auth"

export type PagedResult<T> = {
  items: T[]
  page: number
  pageSize: number
  total: number
}

export type ManagedMember = {
  id: number
  memberCode: string
  fullName: string
  email: string
  phone: string
  status: "active" | "pending" | "expired" | string
  dateOfBirth?: string
  gender?: string
  address?: string
  emergencyContact?: string
}

export type ManagedUser = {
  userId: number
  fullName: string
  email: string
  phone?: string
  role: UserRole
  status: "active" | "locked" | string
  initialPassword?: string
  passwordAutoGenerated?: boolean
}

// Phản chiếu TrainerResponse của backend (TrainersController.List/GetById).
export type ManagedTrainer = {
  id: number
  userId: number
  fullName: string
  email: string
  specialty: string
  status: "active" | "locked" | string
  bio?: string | null
  gender?: string | null
  dateOfBirth?: string | null
  yearsOfExperience?: number | null
  createdAt?: string
}

export type CreateMemberInput = {
  fullName: string
  email: string
  phone: string
  dateOfBirth?: string
  gender?: string
  address?: string
  emergencyContact?: string
}

export type UpdateMemberInput = Partial<CreateMemberInput> & {
  status?: "active" | "pending" | "expired"
}

export type CreateUserInput = {
  fullName: string
  email: string
  phone?: string
  role: "staff" | "pt" | "member"
  password?: string
}

export type UpdateUserInput = Partial<{
  fullName: string
  email: string
  phone: string
  role: "staff" | "pt" | "member"
}>

export type UpdateUserStatusInput = {
  status: "active" | "locked"
}

export type ResetUserPasswordResult = {
  userId: number
  temporaryPassword: string
}

export type CreateTrainerInput = {
  fullName: string
  specialty: string
  userId?: number
}

export type MemberManagementError = {
  code: string
  message: string
}
