import type { UserRole } from "@/types/auth"

export type PagedResult<T> = {
  items: T[]
  page: number
  pageSize: number
  total: number
}

export type ManagedMember = {
  id: number
  memberCode: string
  fullName: string
  email: string
  avatarUrl?: string | null
  phone: string
  status: "active" | "pending" | "expired" | string
  dateOfBirth?: string
  gender?: string
  address?: string
  emergencyContact?: string
}

export type ManagedUser = {
  userId: number
  fullName: string
  email: string
  phone?: string
  role: UserRole
  status: "active" | "locked" | string
  initialPassword?: string
  passwordAutoGenerated?: boolean
  dateOfBirth?: string | null
  gender?: string | null
  address?: string | null
  emergencyContact?: string | null
}

// Phản chiếu TrainerResponse của backend (TrainersController.List/GetById).
export type ManagedTrainer = {
  id: number
  userId: number
  fullName: string
  email: string
  specialty: string
  status: "active" | "locked" | string
  bio?: string | null
  gender?: string | null
  dateOfBirth?: string | null
  address?: string | null
  emergencyContact?: string | null
  yearsOfExperience?: number | null
  createdAt?: string
}

export type CreateMemberInput = {
  fullName: string
  email: string
  phone: string
  dateOfBirth?: string
  gender?: string
  address?: string
  emergencyContact?: string
}

export type UpdateMemberInput = Partial<CreateMemberInput> & {
  status?: "active" | "pending" | "expired"
}

export type CreateUserInput = {
  fullName: string
  email: string
  phone?: string
  role: "staff" | "admin"
  password?: string
}

export type UpdateUserInput = Partial<{
  fullName: string
  email: string
  phone: string
  dateOfBirth: string
  gender: string
  address: string
  emergencyContact: string
}>

export type UpdateUserStatusInput = {
  status: "active" | "locked"
}

export type ResetUserPasswordResult = {
  userId: number
  temporaryPassword: string
}

export type CreateTrainerInput = {
  fullName?: string
  email?: string
  phone?: string
  password?: string
  specialty: string
  bio?: string
  gender?: string
  dateOfBirth?: string
  address?: string
  emergencyContact?: string
  yearsOfExperience?: number
  userId?: number
}

export type UpdateTrainerInput = Partial<{
  specialty: string
  bio: string
  gender: string
  dateOfBirth: string
  yearsOfExperience: number
  address: string
  emergencyContact: string
}>

export type CreateTrainerResult = {
  trainer: ManagedTrainer
  initialPassword: string | null
  passwordAutoGenerated: boolean
  linkedToExistingAccount: boolean
}

export type MemberManagementError = {
  code: string
  message: string
}
